export enum ErrorType {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  BANNED_USER = 'BANNED_USER',
  DELETED_USER = 'DELETED_USER',
  SUSPENDED_USER = 'SUSPENDED_USER',
  UNVERIFIED_USER = 'UNVERIFIED_USER',
  NOT_FOUND = 'NOT_FOUND',
}
